### ISSUE TITLE
[Improvement] Show info for sticky pistons that have air-gapped blocks

### ISSUE THREAD

**Issue by Andrews54757** [Fallen-Breath/pistorder#1]
Hello, I've been using this mod for a while now, and it is very useful. However, I would like to suggest an improvement regarding sticky pistons with air-gapped blocks.

Current behavior:

If you right click on a retracted sticky piston that is not attached to a block, it will display "push" info with 0 blocks even if it would pull blocks had it been powered.

Desired behavior:

If you right click on a retracted sticky piston that is not attached to a block, it will display "retract" info with the right blocks (skipping the air block in front of it).

Screenshots:

(Current behavior)
![2020-12-29_16 56 07](https://user-images.githubusercontent.com/13282284/103316564-e8b6ab00-49f6-11eb-8822-9035aa8b1709.png)

(Desired behavior - without piston being powered)
![2020-12-29_16 56 24](https://user-images.githubusercontent.com/13282284/103316592-f8ce8a80-49f6-11eb-86af-7379e2533f3c.png)

**Comment by Fallen-Breath** [comment]
Would it be better if you can loop between push/retract/none info display mode by just right clicking in this situation? Since it looks weird if it shows retraction info when it's not extended

**Comment by Andrews54757** [comment]
Perhaps that is logical, but I think that displaying information that the sticky piston would push 0 blocks isn't very useful.

**Comment by Fallen-Breath** [comment]
At least it doesn't confuse people, it does push 0 block
